export const mockPokemonDataMapped = [
	{
		id: 1,
		name: 'bulbasaur',
		weight: 69,
		types: ['grass', 'poison'],
		movements: [
			'razor-wind',
			'swords-dance',
			'cut',
			'bind',
			'vine-whip',
			'headbutt',
			'tackle',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/2.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/2.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/2.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png',
	},
	{
		id: 3,
		name: 'venusaur',
		weight: 1000,
		types: ['grass', 'poison'],
		movements: [
			'swords-dance',
			'cut',
			'bind',
			'vine-whip',
			'headbutt',
			'tackle',
			'body-slam',
			'take-down',
			'double-edge',
			'growl',
			'roar',
			'hyper-beam',
			'strength',
			'mega-drain',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/3.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/3.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png',
	},
	{
		id: 4,
		name: 'charmander',
		weight: 85,
		types: ['fire'],
		movements: [
			'mega-punch',
			'fire-punch',
			'thunder-punch',
			'scratch',
			'swords-dance',
			'cut',
			'wing-attack',
			'mega-kick',
			'headbutt',
			'body-slam',
			'take-down',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/4.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/4.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png',
	},
	{
		id: 5,
		name: 'charmeleon',
		weight: 190,
		types: ['fire'],
		movements: [
			'mega-punch',
			'fire-punch',
			'thunder-punch',
			'scratch',
			'swords-dance',
			'cut',
			'mega-kick',
			'headbutt',
			'body-slam',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/5.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/5.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/5.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png',
	},
	{
		id: 6,
		name: 'charizard',
		weight: 905,
		types: ['fire', 'flying'],
		movements: [
			'mega-punch',
			'fire-punch',
			'thunder-punch',
			'scratch',
			'swords-dance',
			'cut',
			'wing-attack',
			'fly',
			'mega-kick',
			'headbutt',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/6.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png',
	},
	{
		id: 7,
		name: 'squirtle',
		weight: 90,
		types: ['water'],
		movements: [
			'mega-punch',
			'ice-punch',
			'mega-kick',
			'headbutt',
			'tackle',
			'body-slam',
			'take-down',
			'double-edge',
			'tail-whip',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/7.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/7.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png',
	},
	{
		id: 8,
		name: 'wartortle',
		weight: 225,
		types: ['water'],
		movements: [
			'double-edge',
			'tail-whip',
			'bite',
			'water-gun',
			'hydro-pump',
			'surf',
			'ice-beam',
			'blizzard',
			'bubble-beam',
			'submission',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/8.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/8.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/8.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png',
	},
	{
		id: 9,
		name: 'blastoise',
		weight: 855,
		types: ['water'],
		movements: [
			'tail-whip',
			'bite',
			'roar',
			'water-gun',
			'hydro-pump',
			'surf',
			'ice-beam',
			'blizzard',
			'bubble-beam',
		],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/9.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/9.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png',
	},
	{
		id: 10,
		name: 'caterpie',
		weight: 29,
		types: ['bug'],
		movements: ['tackle', 'string-shot', 'snore', 'bug-bite', 'electroweb'],
		sprites: [
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10.png',
		],
		imgUri:
			'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/10.png',
	},
];
